### ISSUE TITLE
walpaper displaying as white image

### ISSUE THREAD

**Issue by HelmiDev03** [vivek9patel/vivek9patel.github.io#107]
when i try to add new walpaper in public/images/wallpapers then i add it to the walpepers map in components/apps/settings.js  , it display as white image in the website , although its webp extension and also i make it same dimesnion of other pics

**Comment by ShamyaHaria** [comment]
Update your background-image.js file and if required then lock-screen.js as well.
(Have updated it in your repo and created a pull request, hopefully it works!)
