### ISSUE TITLE
cd and code . Commands not working 

### ISSUE THREAD

**Issue by Devansh-Singh-Parmar** [vivek9patel/vivek9patel.github.io#15]
Please Make these command workable so that It will be more fun

**Comment by vivek9patel** [comment]
cd command is working,
and it'll be wonderful to add 'code .' command.

**Comment by iamkarshe** [comment]
I was so much into UI that after `cd books` I was keep tabbing myself for auto filling. 
Can `Tab` key be mocked to provide terminal-ish autocomplete feature?

**Comment by tusharnankani** [comment]
> I was so much into UI that after `cd books` I was keep tabbing myself for auto filling.
> Can `Tab` key be mocked to provide terminal-ish autocomplete feature?

`Tab` on a terminal makes sense, but on a webpage, `tab` works as to move on focusable elements are links, input fields, and buttons. So, I don't think that can be implemented unless there is a way of disabling the `Tab` key.

**Comment by vivek9patel** [comment]
There is a way to stop default behavior of webpage for tab,
`onKeyDown` event listen for "TAB" & `e.preventDefault()` will do the work!

Although if I implement autocomplete feature, web performance will decrease, because I have to search through all the `child_directories` on every TAB press,
unless if I implement some sort of algorithm to perform search!

**Comment by iamkarshe** [comment]
`Tab` feature would also need `tabindex=-1` to avoid focusable inputs.

You can keep of all directories in one array (which you can ofcourse generate at build time) and use something like `Fuse.js` to fuzzy-fy the searches ( https://fusejs.io/ ).

Let me know your thoughts.

**Comment by vivek9patel** [comment]
hmm, ill look at Fuse.js docs then!

**Comment by Devansh-Singh-Parmar** [comment]
> cd command is working,
> and it'll be wonderful to add 'code .' command.

Hello, I Tried cd command
but it's didn't work...
