### ISSUE TITLE
There is lag while entering commands in terminal after pressing enter

### ISSUE THREAD

**Issue by pavankalyan-codes** [vivek9patel/vivek9patel.github.io#16]
Steps to replicate:

1.Open terminal
2.Press Enter key
3.Now try typing any command.

You can see a blank terminal without out inputted text.

Wait for few seconds. 

Now it will work fine.

Don't know whether it is an issue with my browser. 

Please verify this issue.

**Comment by vivek9patel** [comment]
yes, it's a bug,
it's just that on enter `keyDown` input looses the focus!
I'll fix it!
