### ISSUE TITLE
chrome browser

### ISSUE THREAD

**Issue by Adarshgabani** [vivek9patel/vivek9patel.github.io#18]
in chrome, while you search your own website(vivek9patel.github.io) it will open your website but inside that chrome is not working.
(goto vivek9patel.github.io -----> open chrome ----> search for vivek9patel.github.io ---> open chrome now its(chrome) not working nothing )

**Comment by vivek9patel** [comment]
Yes because iframe is only working in 2 layers 🤷🏻‍♂️
