### ISSUE TITLE
Reflected XSS in terminal

### ISSUE THREAD

**Issue by aramchandran** [vivek9patel/vivek9patel.github.io#19]
Hey,

I found that this website uses a terminal module that allows users to echo text in the terminal. Unfortunately this terminal does not sanitize user input.

If a user enters the following command: `echo <svg><svg onload=alert(0)>`, a Javascript alert pops up on the screen as shown below.

<img width="856" alt="1" src="https://user-images.githubusercontent.com/25450156/115160162-cf4c7400-a064-11eb-9761-a5cca8a7ff6d.png">

This is obviously a non-priority issue because it is not "stored". But a good idea would be to sanitize all user input.

Hope this helps!

**Comment by vivek9patel** [comment]
Oh, i didn't think it through,
I'll convert that soon!
