### ISSUE TITLE
Terminal at https://vivek9patel.github.io/

### ISSUE THREAD

**Issue by rubyFeedback** [vivek9patel/vivek9patel.github.io#20]
(1) Would it be possible for the "ls" implementation to also get -a option? Or any option to display one file per row?

(2) Would it be possible for mkdir() to be added too? It does not have to create a real directory; in ruby we'd probably
use tmpdir or something.

By the way, the idea is quite great. Would be nice if the default "ubuntu" log in at vivek could also show some
"about this project" or so, to detail some design goals you have had. And whether other projects inspired you
as well.

Thanks for reading!

**Comment by vivek9patel** [comment]
Good ideas there,
I'll add:
- mkdir command to add directories 
- An new App for AboutThisProject!

**Comment by vivek9patel** [comment]
- added mkdir #25
