### ISSUE TITLE
feat: Drag and select

### ISSUE THREAD

**Issue by ankithans** [vivek9patel/vivek9patel.github.io#21]
You can add drag and select feature on the desktop. This will give a feel of the full operating system.
like this 

![image](https://user-images.githubusercontent.com/50692897/115194226-ca420000-a10a-11eb-888d-0a680b6bf552.png)

**Comment by iamkarshe** [comment]
_For Desktop utilities/widget such as :_

`Calculator`, 
`Crypto-watch`, 
`Currency Exchange`, 
`Weather`, 
`Quote of the Day`,
`Random Wiki article`,
'History in Today`,
`BBC News Feed`,
`xkcd`

**Comment by iamkarshe** [comment]
_For Desktop more utilities/widgets such as :_

`Calculator`  > Basic functional calculator

`Crypto-watch`  > Watch current exchange rate of various cryptos

`Currency Exchange` > Currency converter 

`Weather` > Weather

`Quote of the Day` > Quote of the Day

`Random Wiki article` > Random Wiki article

`Random Unsplash wallpaper` > Random Desktop wallpaper from Unsplash

`History in Today` > What happened today in the past history

`BBC News Feed / Inshort` > On desktop ballon-type BBC or Inshort news feed

`xkcd` > The comic!
