### ISSUE TITLE
Show Applications doesn't work

### ISSUE THREAD

**Issue by behrad-ahmadpour** [vivek9patel/vivek9patel.github.io#30]
Hi 
Thanks for providing such a wonderful project.

I figure out that Show applications at the bottom of the page don't work. 

if you are ok, I can fix it.

**Comment by vivek9patel** [comment]
Hey @behrad-ahmadpour,
someone already raised a PR for that --> #29

**Comment by behrad-ahmadpour** [comment]
Ok!

Also, can I work on the terminal more command like cat?

**Comment by vivek9patel** [comment]
ya sure!
