### ISSUE TITLE
Add Projects and Resume Icon instead of putting them in About Vivek

### ISSUE THREAD

**Issue by pulkit0007** [vivek9patel/vivek9patel.github.io#31]
Also put icon on left side instead of  Right

**Comment by vivek9patel** [comment]
- i didn't wanted to make user double click and then open multiple folders to see my projects and stuffs, so i put all that in one folder. (friction less)
- on the left side there is sidebar, so icons will be overlapping with that + my local ubuntu layout is identical with my portfolio!
