### ISSUE TITLE
Bug: XSS due to lack of input sanitisation

### ISSUE THREAD

**Issue by k4u5h1k** [vivek9patel/vivek9patel.github.io#32]
## Problem
Terminal input such as `<input/onmouseover="alert('XSS')">` causes an alert to pop up on hovering over the white box.  

## Severity
This is currently a non issue but if a forker decides to make input persistent and/or tries to simulate creation of multiple users this will be very dangerous.

**Comment by thatcatdrout** [comment]
just review the forkers code and everything will be ok!
