### ISSUE TITLE
Add NextJS support

### ISSUE THREAD

**Issue by thatcatdrout** [vivek9patel/vivek9patel.github.io#35]
I tried to switch from ReactJS to NextJS to this project but failed. Please make a  NextJS version of this project because i  want server-side rendering support and other nice benefits. Note:I use this project for my website

**Comment by thatcatdrout** [comment]
dead project

**Comment by thatcatdrout** [comment]
> dead project

i use this for my website lol

**Comment by thatcatdrout** [comment]
Me: finding a really good project
The mantainer: *I'm going to give you up!*

**Comment by vivek9patel** [comment]
ive to learn nextjs first

**Comment by vivek9patel** [comment]
might take some time brother 🤷🏻‍♂️

**Comment by thatcatdrout** [comment]
NextJS is based of ReactJS but i understand. I will close this issue

**Comment by vivek9patel** [comment]
Added NEXT.js!
