### ISSUE TITLE
sidebar overflow when having lots of apps

### ISSUE THREAD

**Issue by fewwwww** [vivek9patel/vivek9patel.github.io#42]
![截屏2021-08-22 上午10 58 40](https://user-images.githubusercontent.com/41555918/130340410-7e7f3a36-22c1-422f-87f6-54c0db6f4ba4.png)

**Comment by fewwwww** [comment]
fixed with 
<img width="1434" alt="截屏2021-08-22 下午11 54 15" src="https://user-images.githubusercontent.com/41555918/130361633-6d8e4b3e-e62b-4099-b849-deed1f66a689.png">

you can also make scrollbar invisible by 
<img width="1292" alt="截屏2021-08-22 下午11 55 22" src="https://user-images.githubusercontent.com/41555918/130361671-70298829-d81d-4117-b78d-d8d1fefb8d63.png">

**Comment by vivek9patel** [comment]
raise a PR?
