### ISSUE TITLE
The panel volume bug

### ISSUE THREAD

**Issue by Zzivh** [vivek9patel/vivek9patel.github.io#5]
The volume and brightness settings in the upper right corner, drag the mouse, the panel will disappear but the function is still valid

**Comment by vivek9patel** [comment]
Yes, I tried solving it many times, but I don't know what the actual problem is,
In Mobile Devices, this issue is not there. Although I can hard code it to prevent closing, I don't want to do that.

**Comment by abhishekadhikari23** [comment]
Check pull request #28 . Fixed it. Also brightness slider will change css "filter: brightness(value);" to actually create the brightness change feature.
