### ISSUE TITLE
Error while running your aplication

### ISSUE THREAD

**Issue by hasthamalp** [vivek9patel/vivek9patel.github.io#63]
i download and run the code using `npm start`,but it shows the error message 

*Failed to compile.*

**./src/components/apps/spotify.js
SyntaxError: C:\Users\Lenovo\Downloads\vivek9patel.github.io-master\src\components\apps\spotify.js: Unexpected character ' '. (1:0)**

**Comment by vivek9patel** [comment]
can you try after pulling latest changes?
also, do `yarn && yarn start` this time

**Comment by hasthamalp** [comment]
NO.I clone your project and try to run on local machine npm install & npm start ,but shows error message .

**Comment by vivek9patel** [comment]
Just tried that,
it runs perfectly for me!
I'd suggest you to re-clone the repository and do `yarn && yarn start`

**Comment by hasthamalp** [comment]
yarn command work for windows

**Comment by vivek9patel** [comment]
yup
it's not depended on any OS.
if it is not installed in your system just run this command, it'll install it globally.
`npm install --global yarn`
