### ISSUE TITLE
Toolbar bug

### ISSUE THREAD

**Issue by kartikkoul** [vivek9patel/vivek9patel.github.io#66]
When you click on toolbar and the drawer opens, after that when you click on the same area above orange bottom border and close the drawer and it does successfully close the drawer. But when see that area it still displays active orange bottom border and also when you click on that area again, the drawer wont open until you click somewhere else on the screen.

**Comment by vivek9patel** [comment]
Hmm, it's because I've put focused-based modal toggling.
I'll fix it
