### ISSUE TITLE
Bug: TypeError: this.props.screen is not a function

### ISSUE THREAD

**Issue by thatcatdrout** [vivek9patel/vivek9patel.github.io#69]
So in /components/base/window.js theres a bug:

Unhandled Runtime Error
TypeError: this.props.screen is not a function

Source
components/base/window.js (291:111) @ WindowMainScreen.render

  289 |     return (
  290 |         <div className={"w-full flex-grow z-20 max-h-full overflow-y-auto windowMainScreen" + (this.state.setDarkBg ? " bg-ub-drk-abrgn " : " bg-ub-cool-grey")}>
> 291 |             {this.props.addFolder ? displayTerminal(this.props.addFolder, this.props.openApp) : this.props.screen()}
      |                                                                                                           ^
  292 |         </div>
  293 |     )
  294 | }
Call Stack
Desktop.eval [as focus]
components/screen/desktop.js (429:13)
eval
components/screen/desktop.js (392:91)
Show collapsed frames

Please fix it asap

**Comment by thatcatdrout** [comment]
Heres my source code: https://github.com/thatcatdrout/debian-web

**Comment by vivek9patel** [comment]
Did you change something in the original source code?

**Comment by thatcatdrout** [comment]
i removed react-ga becuase i dont use Google Analytics. i removed some div elements from vivek.js file becuase i dont use them. I will try to git clone the original repo and try to recustomize it

**Comment by thatcatdrout** [comment]
my vivek js file was weirdly configured so im closing this issue
