### ISSUE TITLE
To Do app

### ISSUE THREAD

**Issue by RedEdge967** [vivek9patel/vivek9patel.github.io#73]
### Hello Vivek!
- I want to say that, If you like, Can you add my To do app as a app in this Ubuntu web experience?
I tried to add to my ubuntu web repo, but it didn't work. Can you add it? If it supports the frame.

Link to my repo : https://github.com/RedEdge967/ubuntu-folio
Link to the To-do app : https://to-do-app-jquery.vercel.app
Link to the preview deployment : https://ubuntu-e8fwz4pqu-chandula-janith.vercel.app/
(This link is the one I tried to add to-do app to my ubuntu web)

![please](https://sdk.bitmoji.com/render/panel/fe4a1c10-cce9-4b4a-a43c-6e707afcc5d1-e22d463a-3212-49f0-9ee5-c11a05d6fa22-v1.png?transparent=1&palette=1&width=246)

**Comment by vivek9patel** [comment]
hey!
Thanks for the suggestion, but as for now, I want to keep this Ubuntu web experience as classic as I can.
Your TO-DO app has nice animations, but it'll not go with Ubuntu UI as they don't have any specific TO-DO app.

**Comment by RedEdge967** [comment]
Okay. thank you!

Have a Nice day!
