### ISSUE TITLE
Dark mode doesn't capture all text

### ISSUE THREAD

**Issue by ajmeese7** [vivek9patel/vivek9patel.github.io#86]
Hey Vivek, quick issue I noticed that I wanted to point out. On the portfolio application, your `GitHub Sponsor` portion under the `Projects` section has black text on a black background:

![black on black](https://user-images.githubusercontent.com/17814535/178374927-55dd1c5a-4238-4779-873e-381ec4975f30.png)

**Comment by vivek9patel** [comment]
That shouldn't happen.
Thanks for pointing it out, will fix it!

**Comment by vivek9patel** [comment]
Can you check if that is still happening? works for me
Or if you can send me your environment (browser, os, etc.), that'll be great
<img width="1440" alt="Screenshot 2022-07-15 at 1 47 05 PM" src="https://user-images.githubusercontent.com/50517245/179182773-c26cc384-4db8-4ce2-99d8-c42f6c7bae39.png">

**Comment by ajmeese7** [comment]
I'm still experiencing the same issue, and I have caching disabled for my browser so if the changes are live on the site I can't tell the difference.

Browser: `Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)`
Operating System: ZorinOS 16 Pro

**Comment by vivek9patel** [comment]
I tried it in a different browser, and it is working fine for me.
Closing the issue for now, let me know if you still face it in any other browser!
