### ISSUE TITLE
App Windows do not render properly on Safari

### ISSUE THREAD

**Issue by onclave** [vivek9patel/vivek9patel.github.io#9]
The application windows on your site do not render properly on the Safari browser on a mac or iPhone. You might want to look into that. They render in a very small portion of the window. Maybe a width or flex issue. Safari has this issue if you have overlapping or overriding flex-box rules in your CSS which other browsers like Chrome and FF just ignore. I face this issue often with my projects.

I would have provided a pull request for the fix but I don't work in React. (Angular *cough* *cough*)

Safari Version 14.0.3 (16610.4.3.1.7)
macOS Big Sur Version 11.2.3

 By the way, insane website you got. Love it. Work perfectly fine on Chrome and FF.

I'm attaching screenshots for the issue.

![Screenshot 2021-04-17 at 11 34 34 PM](https://user-images.githubusercontent.com/11374405/115122733-19871400-9fd7-11eb-9fb9-44480c71d678.png)
![Screenshot 2021-04-17 at 11 34 29 PM](https://user-images.githubusercontent.com/11374405/115122738-20158b80-9fd7-11eb-8833-7374a54dcf66.png)
![Screenshot 2021-04-17 at 11 34 17 PM](https://user-images.githubusercontent.com/11374405/115122739-21df4f00-9fd7-11eb-972a-18895c0a0047.png)

**Comment by vivek9patel** [comment]
Yes im still figuring out what to do,
Even the desktop apps renders on the left side in some of the iphones!
Will fix it as soon as i find some sort of solution for this!

**Comment by vivek9patel** [comment]
It should be fixed now!
